# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d842d6da6c83851553cf0fbaca82b7d7"
application_url = "https://example.com"
embedded = true
name = "product-manager-app"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[webhooks]
api_version = "2026-10"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
